# Generated by Django 5.0.4 on 2024-06-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_order_email_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
